[project]
name = "nav-union"
version = '0.1.0'
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Espen Holtebu", email = "espen.holtebu@nav.no" }
]
requires-python = ">=3.12"
dependencies = [
    "flyte>=2.6.13",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
